### ISSUE TITLE
java.lang.ClassNotFoundException: Query

### ISSUE THREAD

**Issue by wiqijan2002** [tyrex-team/sparqlgx#2]
I am trying to run a SPARQLGX
![sparqlgxerror](https://user-images.githubusercontent.com/38495673/72321033-cfc9c280-36dd-11ea-85a3-2897ebc97adb.png)
 but stuck in one step. when I tried to query a loaded dataset. it gives the attached error. Will, you plz help in this regard. Your help will be greatly appreciated.

**Comment by tcalmant** [comment]
Hi,
Did you run `./compile.sh` at the root of the repository ?
This script compiles the `bin/sparqlgx-translator` tool, which is required by the other scripts.

**Comment by wiqijan2002** [comment]
yes i did compile at the root. please have a look at the snapshot to get an idea
![newsparqlgx](https://user-images.githubusercontent.com/38495673/72433346-139ef380-37d4-11ea-9e02-c4a06c6179d4.png)
![snapshot](https://user-images.githubusercontent.com/38495673/72433462-4ea12700-37d4-11ea-87a9-d5b0c4d0a71c.png)
plz have a look at the files in the bin folder

**Comment by louisjac** [comment]
Hi,

According to the screenshot you do not have ocamlfind. It usually comes with the OCaml distribution but you can install it manually (with opam for instance).

**Comment by wiqijan2002** [comment]
yes i did compile at the root. please have a look at the snapshot to get an idea
![newsparqlgx](https://user-images.githubusercontent.com/38495673/72433346-139ef380-37d4-11ea-9e02-c4a06c6179d4.png)
![snapshot](https://user-images.githubusercontent.com/38495673/72433462-4ea12700-37d4-11ea-87a9-d5b0c4d0a71c.png)
plz have a look at the files in the bin folder
